# 网站的根地址，必须设置为您的域名
baseURL = 'https://cheerchen.me/'
# 网站的默认语言
languageCode = 'zh-Hans'
defaultContentLanguage = 'zh'
# 网站的标题
title = 'CheerChen 的博客'

# 使用的主题
theme = 'dream'

hasCJKLanguage = true
enableRobotsTXT = true

[markup]
[markup.highlight]
noClasses = false
lineNos = true
lineNumbersInTable = false
anchorLineNos = false
codeFences = true
guessSyntax = true
tabWidth = 4

[params.advanced]
customCSS = ["custom.css"]

[params]
headerTitle = "CheerChen's Blog"
motto = "在日程序员的技术分享，杂谈和生活记录"
# 您的作者名
author = "CheerChen"
# 您的头像，同样，请将图片放在项目根目录下的 static 文件夹里
avatar = "3284997.png"

customSyntaxHighlighting = true

lightTheme = "emerald"
darkTheme = "forest"

showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
favicon = "favicon.ico"

# -- 开启禅定模式 --
# zenMode = true

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"

# Sitemap 配置
[sitemap]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"

# 允许 HTML 标签，用于结构化数据
[markup.goldmark.renderer]
unsafe = true

[services]
[services.googleAnalytics]
ID = 'G-GVR7W9ZBBP'
