# 网站的根地址，必须设置为您的域名
baseURL = 'https://cheerchen.me/'
# 网站的默认语言
languageCode = 'zh-Hans'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false
# 网站的标题
title = "CheerChen's Blog"

# 使用的主题
theme = 'dream'

hasCJKLanguage = true
enableRobotsTXT = true

# 多语言配置
[languages]
  [languages.zh]
    languageCode = 'zh-Hans'
    languageName = 'ZH'
    title =  "CheerChen's Blog"
    weight = 1
    [languages.zh.params]
      headerTitle = "CheerChen's Blog"
      motto = "在日程序员的技术分享，杂谈和生活记录"
      author = "CheerChen"
      avatar = "3284997.png"
      description = "CheerChen 的技术博客，专注于云原生、Kubernetes、AWS、AI 等前沿技术分享"
      
  [languages.ja]
    languageCode = 'ja'
    languageName = 'JP'
    title =  "CheerChen's Blog"
    weight = 2
    [languages.ja.params]
      headerTitle = "CheerChen's Blog"
      motto = "クラウドネイティブ・AI、技術共有、雑談"
      author = "CheerChen"
      avatar = "3284997.png"
      description = "クラウドネイティブ、Kubernetes、AWS、AI などなど"

[markup]
[markup.highlight]
noClasses = false
lineNos = true
lineNumbersInTable = false
anchorLineNos = false
codeFences = true
guessSyntax = true
tabWidth = 4

[params.advanced]
customCSS = ["custom.css"]

[params]
customSyntaxHighlighting = true
lightTheme = "emerald"
darkTheme = "forest"
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
favicon = "favicon.ico"

# -- 开启禅定模式 --
# zenMode = true

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"

# Sitemap 配置
[sitemap]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"

# 允许 HTML 标签，用于结构化数据
[markup.goldmark.renderer]
unsafe = true

[services]
[services.googleAnalytics]
ID = 'G-GVR7W9ZBBP'
