# 网站的根地址，必须设置为您的域名
baseURL = 'https://cheerchen.me/'
# 网站的默认语言
defaultContentLanguage = 'zh'
# 网站的标题
title = 'CheerChen 的博客'
# 使用的主题
theme = 'dream'
lightTheme = "emerald"
darkTheme = "forest"

[params.advanced]
customCSS = ["custom.css"]

[params]
# 您的作者名
author = "CheerChen"
# 您的头像，同样，请将图片放在项目根目录下的 static 文件夹里
avatar = "/5109459.png"

# -- 开启禅定模式 --
zenMode = true

[params.article]
showToc = true
